### ISSUE TITLE
No module named 'utils

### ISSUE THREAD

**Issue by Dahandla** [devsisters/DQN-tensorflow#19]
when i try to run 
   python main.py --env_name=Breakout-v0 --is_train=True

i get this error 

Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from dqn.agent import Agent
  File "/home/dahandla/DQN-tensorflow-master/dqn/agent.py", line 10, in <module>
    from .replay_memory import ReplayMemory
  File "/home/dahandla/DQN-tensorflow-master/dqn/replay_memory.py", line 8, in <module>
    from utils import save_npy, load_npy
ImportError: No module named 'utils'

any help would be appreciated

**Comment by carpedm20** [comment]
Fixed.
