### ISSUE TITLE
AttributeError: 'TimeLimit' object has no attribute 'ale' 

### ISSUE THREAD

**Issue by minimok7** [devsisters/DQN-tensorflow#25]
Hi, I downloaded the codes, and then test it as it described here.
However, I got this error as follows,
I think, all requirements are installed except opencv2 and openAI gym was tested.
I would appreciate that someone finds the cause and the solution.

Traceback (most recent call last):
File "/DQN-tensorflow-master/main.py", line 69, in
tf.app.run()
File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
sys.exit(main(sys.argv[:1] + flags_passthrough))
File "/DQN-tensorflow-master/main.py", line 64, in main
agent.train()
File "/DQN-tensorflow-master/dqn/agent.py", line 40, in train
screen, reward, action, terminal = self.env.new_random_game()
File /DQN-tensorflow-master/dqn/environment.py", line 28, in new_random_game
self.new_game(True)
File "/DQN-tensorflow-master/dqn/environment.py", line 21, in new_game
if self.lives == 0:
File "/DQN-tensorflow-master/dqn/environment.py", line 52, in lives
return self.env.ale.lives()
AttributeError: 'TimeLimit' object has no attribute 'ale'

**Comment by KingAndQueen** [comment]
Could you share how did you solve this problem? I face the same error.

**Comment by yulequan** [comment]
I face the same error too.

**Comment by Lan1991Xu** [comment]
HI guys， just change the old gym 0.7.0

**Comment by amrqura** [comment]
pip install gym==0.7.0

Solve the problem.
