### ISSUE TITLE
I got error about use_gpu flag..... Could you help me out, please?

### ISSUE THREAD

**Issue by wonchul-kim** [devsisters/DQN-tensorflow#27]
Traceback (most recent call last):
  File "main.py", line 69, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "main.py", line 56, in main
    raise Exception("use_gpu flag is true when no GPUs are available")
Exception: use_gpu flag is true when no GPUs are available

The above is the error message.

Could you help me out??

**Comment by serialx** [comment]
Please execute main.py with `--use_gpu=False`

**Comment by cypreess** [comment]
If you have gpu and its configured properly (e.g. Nvidia gpu require propriate drivers and cudnn library installed) than you probably should install `pip install tensorflow_gpu` package rather than `tensorflow`. Error like that might happen that you have tensorflow installed without gpu support (will always return `False` when checking if GPU is installed.
