### ISSUE TITLE
error memory

### ISSUE THREAD

**Issue by damienlancry** [devsisters/DQN-tensorflow#52]
When i do :
`python main.py --is_train=False --display=True --use_gpu=False`

I get :
`
[*] GPU : 1.0000
[2018-05-23 17:17:55,692] Making new env: Breakout-v0
{'_save_step': 500000,
'_test_step': 50000,
'action_repeat': 4,
'backend': 'tf',
'batch_size': 32,
'cnn_format': 'NHWC',
'discount': 0.99,
'display': True,
'double_q': False,
'dueling': False,
'env_name': 'Breakout-v0',
'env_type': 'detail',
'ep_end': 0.1,
'ep_end_t': 1000000,
'ep_start': 1.0,
'history_length': 4,
'learn_start': 50000.0,
'learning_rate': 0.00025,
'learning_rate_decay': 0.96,
'learning_rate_decay_step': 50000,
'learning_rate_minimum': 0.00025,
'max_delta': 1,
'max_reward': 1.0,
'max_step': 50000000,
'memory_size': 1000000,
'min_delta': -1,
'min_reward': -1.0,
'model': 'm1',
'random_start': 30,
'scale': 10000,
'screen_height': 84,
'screen_width': 84,
'target_q_update_step': 10000,
'train_frequency': 4}
Traceback (most recent call last):
File "main.py", line 70, in
tf.app.run()
File "/Tuto_DQN/env/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
sys.exit(main(sys.argv[:1] + flags_passthrough))
File "main.py", line 62, in main
agent = Agent(config, env, sess)
File "/Tuto_DQN/tuto_dqn/DQN-tensorflow/dqn/agent.py", line 23, in init
self.memory = ReplayMemory(self.config, self.model_dir)
File "/Tuto_DQN/tuto_dqn/DQN-tensorflow/dqn/replay_memory.py", line 18, in init
self.screens = np.empty((self.memory_size, config.screen_height, config.screen_width), dtype = np.float16)
MemoryError
`
I installed all the dependencies according to the issue #44 Add requirements.txt or alternative
I am running it on my laptop which is a samsung series 7 ultra notebook

Could someone advise me on how to overcome this issue? any comment would be highly appreciated
Thanks a lot!!

**Comment by rahul13ramesh** [comment]
Reduce the value of `memory_size` in the config.py (see [here](https://github.com/devsisters/DQN-tensorflow/blob/c7b1f1051dfa152530322445fc8febb9a2ea078b/config.py#L6)). The memory error is probably caused due to a large replay-memory size.
